services:
  - type: web
    name: mern-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://kelvin:Kelvin12345@cluster0.kad2wwc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
